// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EncaladaD_ExamenProgreso_1.Migrations
{
    [DbContext(typeof(DBSqlSERVER_Demo01))]
    partial class DBSqlSERVER_Demo01ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EncaladaD_ExamenProgreso_1.Models.Cliente", b =>
                {
                    b.Property<string>("clienteId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("esMiembro")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("numeroTelefono")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<decimal>("pagosRealizado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("clienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("EncaladaD_ExamenProgreso_1.Models.Recompensas", b =>
                {
                    b.Property<int>("recompensasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("recompensasId"));

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("puntosAcumulados")
                        .HasColumnType("int");

                    b.HasKey("recompensasId");

                    b.ToTable("PlanRecompensasCliente");
                });

            modelBuilder.Entity("EncaladaD_ExamenProgreso_1.Models.Reserva", b =>
                {
                    b.Property<int>("reservaId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reservaId"));

                    b.Property<string>("clienteId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("fechaEntrada")
                        .HasColumnType("int");

                    b.Property<int>("fechaSalida")
                        .HasColumnType("int");

                    b.Property<decimal>("valorPagar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("reservaId");

                    b.HasIndex("clienteId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("EncaladaD_ExamenProgreso_1.Models.Reserva", b =>
                {
                    b.HasOne("EncaladaD_ExamenProgreso_1.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EncaladaD_ExamenProgreso_1.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
